SELECT ORD_1.*,ORD_2.ORDER_TOTAL_AMOUNT,
  (TAX_POINT * ORD_2.ORDER_TOTAL_AMOUNT)/100 TAX_RATE FROM
(
SELECT * FROM sale_order where (ORDER_NO = :ORDER_NO OR :ORDER_NO ='')
AND (CUSTOMER=:CUSTOMER OR :CUSTOMER='') AND (CREATE_USER=:CREATE_USER OR :CREATE_USER='')
ORDER BY MODIFY_DATE_TIME DESC
)ORD_1
INNER JOIN
(
  SELECT SUM(TOTAL_AMOUNT)ORDER_TOTAL_AMOUNT,SALE_ORDER_NO
    FROM SALE_ORDER_PRODUCT
    GROUP BY SALE_ORDER_NO
)ORD_2 ON ORD_1.ORDER_NO=ORD_2.SALE_ORDER_NO